### ISSUE TITLE
Sugestão na organização do projeto 

### ISSUE THREAD

**Issue by HomeniqueM** [Programando-o-Mundo/Microfundamentos-Compiladores#1]
Talvez para ficar mais organizado renomear as pasta informando o número na frente dela para indicar qual é a sequenciar a ser seguida pode ajudar bastante

Exemplo
00 -  FTC
01 - introdução 
02 - ...

**Comment by GustavoLR548** [comment]
Ola @HomeniqueM , agradeço a sugestão, porém acredito que este tipo de hierarquia não é muito necessária no repositório em si.

O github é mais uma plataforma para armazenar as pastas e os arquivos de Markdown com o conteúdo do material. Enquanto o Gitbook, sendo a plataforma já direcionada e recomendada para o consumo desse material já está organizada com uma sequência ser seguida ( assim como você bem sugere ).

Fazer esse tipo de organização dentro do Github não ajudaria muito e na verdade traria mais inconveniência caso a pessoa gostaria de atualizar aulas que estão entre duas aulas em uma lista. Por exemplo:

Vamos supor que temos uma organização da seguinte maneira:

```
00 - Ordenação Interna
01 - Quicksort
02 - MergeSort
03 - SelectionSort
04 - InsertionSort
05 - CoutingSort
```

Agora vamos supor que queremos adicionar uma aula explicando complexidade de tempo e espaço, obviamente a aula teria de vir antes de qualquer explicação sobre algoritmos de ordenação. Porém isso implica mudar não só a lista toda:


```
00 - Ordenação Interna
01 - Complexidade de Tempo e espaço
02 - Quicksort
03 - MergeSort
04 - SelectionSort
05 - InsertionSort
06 - CoutingSort
```

Como também eu teria que mudar todo o indexamento das páginas no sumário do gitbook para que as páginas possam aparecer corretamente.

Enfim espero que tenha ficado bem explicado.
